# Generated by Django 3.1.7 on 2021-03-21 19:41

import Account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0002_useraccount_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='PicPofile',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=Account.models.create_path),
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PartyName', models.CharField(blank=True, max_length=255, null=True)),
                ('PartyAcronym', models.CharField(blank=True, max_length=255, null=True)),
                ('PartyEmail', models.CharField(blank=True, max_length=255, null=True)),
                ('Username', models.CharField(blank=True, max_length=255, null=True)),
                ('Password', models.CharField(blank=True, max_length=255, null=True)),
                ('Logo', models.FileField(blank=True, max_length=255, null=True, upload_to=Account.models.create_path)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
