# Generated by Django 3.1.7 on 2021-03-21 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20210321_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='Party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.party'),
        ),
    ]
