# Generated by Django 3.1.7 on 2021-03-22 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_useraccount_party'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'permissions': [('voter', 'Voter')]},
        ),
        migrations.AlterModelOptions(
            name='useraccount',
            options={'permissions': [('party', 'Party')]},
        ),
    ]
