# Generated by Django 3.1.7 on 2021-03-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(blank=True, max_length=255, null=True)),
                ('Status', models.CharField(blank=True, choices=[('open', 'Open'), ('close', 'Close')], max_length=255, null=True)),
            ],
        ),
    ]
