# Generated by Django 3.1.7 on 2021-03-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Election', '0003_auto_20210322_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionposition',
            name='Status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='pending', max_length=255),
        ),
    ]
