# Generated by Django 3.1.7 on 2021-03-22 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20210322_2123'),
        ('Election', '0004_auto_20210322_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ElectionState', models.CharField(blank=True, max_length=255, null=True)),
                ('ElectionYear', models.CharField(blank=True, max_length=255, null=True)),
                ('ElectionParty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.party')),
            ],
        ),
        migrations.AlterField(
            model_name='electionposition',
            name='Status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='closed', max_length=255),
        ),
        migrations.CreateModel(
            name='Electionvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ElectionYear', models.CharField(blank=True, max_length=255, null=True)),
                ('ElectionCandidateID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Election.electioncandidate')),
                ('ElectionParty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.useraccount')),
                ('ElectionPositionID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Election.electionposition')),
            ],
        ),
        migrations.AddField(
            model_name='electioncandidate',
            name='ElectionPositionID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Election.electionposition'),
        ),
        migrations.AddField(
            model_name='electioncandidate',
            name='Election_Candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.useraccount'),
        ),
    ]
