# Generated by Django 3.1.7 on 2021-03-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Election', '0006_electioncandidate_electionmanifestoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electionvote',
            old_name='ElectionParty',
            new_name='ElectionUser',
        ),
        migrations.RemoveField(
            model_name='electionvote',
            name='ElectionPositionID',
        ),
    ]
